--
-- Fichier g�n�r� par SQLiteStudio v3.3.3 sur jeu. juil. 14 14:28:06 2022
--
-- Encodage texte utilis� : System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table : adherent
DROP TABLE IF EXISTS adherent;
CREATE TABLE `adherent` (
  `ID_ADHERENT` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `NOM` char(32) DEFAULT NULL,
  `PRENOM` char(32) DEFAULT NULL,
  `TEL` char(32) DEFAULT NULL,
  `SEXE` char(1) NOT NULL,
  `ADRESSE` char(32) DEFAULT NULL
);

-- Table : auteur
DROP TABLE IF EXISTS auteur;
CREATE TABLE `auteur` (
  `ID_AUTEUR` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `NOM` char(32) DEFAULT NULL,
  `PRENOM` char(32) DEFAULT NULL
);
INSERT INTO auteur (ID_AUTEUR, NOM, PRENOM) VALUES (1, 'sagueu', 'dilane');
INSERT INTO auteur (ID_AUTEUR, NOM, PRENOM) VALUES (2, 'mpoudi', 'evelyne');

-- Table : emprunter
DROP TABLE IF EXISTS emprunter;
CREATE TABLE emprunter (ID_EXEMPLAIRE INTEGER NOT NULL, ID_ADHERENT INTEGER NOT NULL, DATE_EMPRUNT date DEFAULT NULL NOT NULL, DATE_RETOUR_PREVU date DEFAULT NULL, STATUT BOOLEAN DEFAULT (0), DATE_RETOUR_EFFECTIF DATE NOT NULL,  FOREIGN KEY (ID_EXEMPLAIRE) REFERENCES exemplaire (ID_EXEMPLAIRE) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (ID_ADHERENT) REFERENCES adherent (ID_ADHERENT) ON DELETE SET NULL ON UPDATE CASCADE);

-- Table : exemplaire
DROP TABLE IF EXISTS exemplaire;
CREATE TABLE exemplaire (ID_EXEMPLAIRE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ID_LIVRE INTEGER NOT NULL, DATE_ARRIVER date DEFAULT NULL, ETAT char (32) DEFAULT NULL, FOREIGN KEY (ID_LIVRE) REFERENCES livre (ID_LIVRE) ON DELETE SET NULL ON UPDATE CASCADE);

-- Table : livre
DROP TABLE IF EXISTS livre;
CREATE TABLE livre (ID_LIVRE INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ID_AUTEUR INTEGER NOT NULL, TITRE char (32) DEFAULT NULL, PHOTO char (32) DEFAULT NULL, FOREIGN KEY (ID_AUTEUR) REFERENCES auteur (ID_AUTEUR) ON DELETE SET NULL ON UPDATE CASCADE);
INSERT INTO livre (ID_LIVRE, ID_AUTEUR, TITRE, PHOTO) VALUES (1, 1, 'Le futur sera ce que nous en ferons', NULL);
INSERT INTO livre (ID_LIVRE, ID_AUTEUR, TITRE, PHOTO) VALUES (10, 1, 'Le futur sera ce que nous en ferons', NULL);
INSERT INTO livre (ID_LIVRE, ID_AUTEUR, TITRE, PHOTO) VALUES (2, 1, 'Le futur sera ce que nous en ferons', NULL);
INSERT INTO livre (ID_LIVRE, ID_AUTEUR, TITRE, PHOTO) VALUES (3, 1, 'Le futur sera ce que nous en ferons', NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
